# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode7.3
notifications:
  email: false
podfile: Example/Podfile
before_install:
- rvm --default use 2.2
install:
- bundle install
- bundle exec pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild build -workspace Example/SGASScreenRecorderDemo.xcworkspace -scheme SGASScreenRecorderDemo -sdk iphoneos ONLY_ACTIVE_ARCH=NO | xcpretty
